[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
evm_version = "shanghai"

[profile.default.fuzz]
seed = 1

[profile.default.invariant]
runs = 256 # default == 256
depth = 15 # default == 15

[rpc_endpoints]
mainnet = "${ALCHEMY_ETH_API_URL}" 
goerli = "${GOERLI_RPC_URL}" 
sepolia = "${SEPOLIA_RPC_URL}" 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# NOTE Project is using prettier formatting, as opposed to forge.
# See more format options https://book.getfoundry.sh/reference/config/formatter
# [fmt]
# line_length = 120
# tab_width = 4
# bracket_spacing = false
# int_types = "long"
# # If function parameters are multiline then always put the function attributes on separate lines
# func_attrs_with_params_multiline = false
# multiline_func_header = "params_first"
# quote_style = "double"
# number_underscore = "thousands"
