/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface LibBalanceInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "InternalBalanceChanged"): EventFragment;
}

export namespace InternalBalanceChangedEvent {
  export type InputTuple = [
    account: AddressLike,
    token: AddressLike,
    delta: BigNumberish
  ];
  export type OutputTuple = [account: string, token: string, delta: bigint];
  export interface OutputObject {
    account: string;
    token: string;
    delta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibBalance extends BaseContract {
  connect(runner?: ContractRunner | null): LibBalance;
  waitForDeployment(): Promise<this>;

  interface: LibBalanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "InternalBalanceChanged"
  ): TypedContractEvent<
    InternalBalanceChangedEvent.InputTuple,
    InternalBalanceChangedEvent.OutputTuple,
    InternalBalanceChangedEvent.OutputObject
  >;

  filters: {
    "InternalBalanceChanged(address,address,int256)": TypedContractEvent<
      InternalBalanceChangedEvent.InputTuple,
      InternalBalanceChangedEvent.OutputTuple,
      InternalBalanceChangedEvent.OutputObject
    >;
    InternalBalanceChanged: TypedContractEvent<
      InternalBalanceChangedEvent.InputTuple,
      InternalBalanceChangedEvent.OutputTuple,
      InternalBalanceChangedEvent.OutputObject
    >;
  };
}
