/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as implementations from "./implementations";
export type { implementations };
export type { Oracle } from "./Oracle";
