/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface SoloAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "getBalance"
      | "getOwner"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "loadFromPosition"
      | "loadFromUser"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "unloadToPosition"
      | "unloadToUser"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoadedFromPosition"
      | "LoadedFromUser"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UnloadedToPosition"
      | "UnloadedToUser"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loadFromPosition",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loadFromUser",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unloadToPosition",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unloadToUser",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loadFromPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loadFromUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unloadToPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unloadToUser",
    data: BytesLike
  ): Result;
}

export namespace LoadedFromPositionEvent {
  export type InputTuple = [
    assetData: BytesLike,
    amount: BigNumberish,
    parameters: BytesLike
  ];
  export type OutputTuple = [
    assetData: string,
    amount: bigint,
    parameters: string
  ];
  export interface OutputObject {
    assetData: string;
    amount: bigint;
    parameters: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoadedFromUserEvent {
  export type InputTuple = [
    assetData: BytesLike,
    amount: BigNumberish,
    parameters: BytesLike
  ];
  export type OutputTuple = [
    assetData: string,
    amount: bigint,
    parameters: string
  ];
  export interface OutputObject {
    assetData: string;
    amount: bigint;
    parameters: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnloadedToPositionEvent {
  export type InputTuple = [
    position: AddressLike,
    assetData: BytesLike,
    amount: BigNumberish,
    parameters: BytesLike
  ];
  export type OutputTuple = [
    position: string,
    assetData: string,
    amount: bigint,
    parameters: string
  ];
  export interface OutputObject {
    position: string;
    assetData: string;
    amount: bigint;
    parameters: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnloadedToUserEvent {
  export type InputTuple = [
    assetData: BytesLike,
    amount: BigNumberish,
    parameters: BytesLike
  ];
  export type OutputTuple = [
    assetData: string,
    amount: bigint,
    parameters: string
  ];
  export interface OutputObject {
    assetData: string;
    amount: bigint;
    parameters: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoloAccount extends BaseContract {
  connect(runner?: ContractRunner | null): SoloAccount;
  waitForDeployment(): Promise<this>;

  interface: SoloAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  getBalance: TypedContractMethod<
    [assetData: BytesLike, parameters: BytesLike],
    [bigint],
    "view"
  >;

  getOwner: TypedContractMethod<[parameters: BytesLike], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  loadFromPosition: TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "payable"
  >;

  loadFromUser: TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "payable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unloadToPosition: TypedContractMethod<
    [
      position: AddressLike,
      assetData: BytesLike,
      amount: BigNumberish,
      parameters: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  unloadToUser: TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [assetData: BytesLike, parameters: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[parameters: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "loadFromPosition"
  ): TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "loadFromUser"
  ): TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unloadToPosition"
  ): TypedContractMethod<
    [
      position: AddressLike,
      assetData: BytesLike,
      amount: BigNumberish,
      parameters: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unloadToUser"
  ): TypedContractMethod<
    [assetData: BytesLike, amount: BigNumberish, parameters: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LoadedFromPosition"
  ): TypedContractEvent<
    LoadedFromPositionEvent.InputTuple,
    LoadedFromPositionEvent.OutputTuple,
    LoadedFromPositionEvent.OutputObject
  >;
  getEvent(
    key: "LoadedFromUser"
  ): TypedContractEvent<
    LoadedFromUserEvent.InputTuple,
    LoadedFromUserEvent.OutputTuple,
    LoadedFromUserEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UnloadedToPosition"
  ): TypedContractEvent<
    UnloadedToPositionEvent.InputTuple,
    UnloadedToPositionEvent.OutputTuple,
    UnloadedToPositionEvent.OutputObject
  >;
  getEvent(
    key: "UnloadedToUser"
  ): TypedContractEvent<
    UnloadedToUserEvent.InputTuple,
    UnloadedToUserEvent.OutputTuple,
    UnloadedToUserEvent.OutputObject
  >;

  filters: {
    "LoadedFromPosition(bytes,uint256,bytes)": TypedContractEvent<
      LoadedFromPositionEvent.InputTuple,
      LoadedFromPositionEvent.OutputTuple,
      LoadedFromPositionEvent.OutputObject
    >;
    LoadedFromPosition: TypedContractEvent<
      LoadedFromPositionEvent.InputTuple,
      LoadedFromPositionEvent.OutputTuple,
      LoadedFromPositionEvent.OutputObject
    >;

    "LoadedFromUser(bytes,uint256,bytes)": TypedContractEvent<
      LoadedFromUserEvent.InputTuple,
      LoadedFromUserEvent.OutputTuple,
      LoadedFromUserEvent.OutputObject
    >;
    LoadedFromUser: TypedContractEvent<
      LoadedFromUserEvent.InputTuple,
      LoadedFromUserEvent.OutputTuple,
      LoadedFromUserEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UnloadedToPosition(address,bytes,uint256,bytes)": TypedContractEvent<
      UnloadedToPositionEvent.InputTuple,
      UnloadedToPositionEvent.OutputTuple,
      UnloadedToPositionEvent.OutputObject
    >;
    UnloadedToPosition: TypedContractEvent<
      UnloadedToPositionEvent.InputTuple,
      UnloadedToPositionEvent.OutputTuple,
      UnloadedToPositionEvent.OutputObject
    >;

    "UnloadedToUser(bytes,uint256,bytes)": TypedContractEvent<
      UnloadedToUserEvent.InputTuple,
      UnloadedToUserEvent.OutputTuple,
      UnloadedToUserEvent.OutputObject
    >;
    UnloadedToUser: TypedContractEvent<
      UnloadedToUserEvent.InputTuple,
      UnloadedToUserEvent.OutputTuple,
      UnloadedToUserEvent.OutputObject
    >;
  };
}
