/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type BlueprintStruct = {
  publisher: AddressLike;
  data: BytesLike;
  maxNonce: BigNumberish;
  startTime: BigNumberish;
  endTime: BigNumberish;
};

export type BlueprintStructOutput = [
  publisher: string,
  data: string,
  maxNonce: bigint,
  startTime: bigint,
  endTime: bigint
] & {
  publisher: string;
  data: string;
  maxNonce: bigint;
  startTime: bigint;
  endTime: bigint;
};

export type SignedBlueprintStruct = {
  blueprint: BlueprintStruct;
  blueprintHash: BytesLike;
  signature: BytesLike;
};

export type SignedBlueprintStructOutput = [
  blueprint: BlueprintStructOutput,
  blueprintHash: string,
  signature: string
] & {
  blueprint: BlueprintStructOutput;
  blueprintHash: string;
  signature: string;
};

export type PluginReferenceStruct = {
  addr: AddressLike;
  parameters: BytesLike;
};

export type PluginReferenceStructOutput = [addr: string, parameters: string] & {
  addr: string;
  parameters: string;
};

export type BorrowerConfigStruct = {
  initCollateralRatio: BigNumberish;
  positionParameters: BytesLike;
};

export type BorrowerConfigStructOutput = [
  initCollateralRatio: bigint,
  positionParameters: string
] & { initCollateralRatio: bigint; positionParameters: string };

export type FillStruct = {
  account: PluginReferenceStruct;
  loanAmount: BigNumberish;
  takerIdx: BigNumberish;
  loanAssetIdx: BigNumberish;
  collAssetIdx: BigNumberish;
  factoryIdx: BigNumberish;
  isOfferFill: boolean;
  borrowerConfig: BorrowerConfigStruct;
};

export type FillStructOutput = [
  account: PluginReferenceStructOutput,
  loanAmount: bigint,
  takerIdx: bigint,
  loanAssetIdx: bigint,
  collAssetIdx: bigint,
  factoryIdx: bigint,
  isOfferFill: boolean,
  borrowerConfig: BorrowerConfigStructOutput
] & {
  account: PluginReferenceStructOutput;
  loanAmount: bigint;
  takerIdx: bigint;
  loanAssetIdx: bigint;
  collAssetIdx: bigint;
  factoryIdx: bigint;
  isOfferFill: boolean;
  borrowerConfig: BorrowerConfigStructOutput;
};

export interface BookkeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BLUEPRINT_TYPEHASH"
      | "PROTOCOL_NAME"
      | "PROTOCOL_VERSION"
      | "agreementClosed"
      | "closePosition"
      | "destroyBlueprint"
      | "domainSeparator"
      | "fillOrder"
      | "getBlueprintHash"
      | "getChainId"
      | "isValidSignature"
      | "isValidSignatureNow"
      | "liquidationLock"
      | "packDataField"
      | "publishBlueprint"
      | "triggerLiquidation"
      | "unpackDataField"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DestroyedBlueprint"
      | "OrderFilled"
      | "PositionClosed"
      | "PositionLiquidated"
      | "PublishedBlueprint"
      | "UsedBlueprint"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BLUEPRINT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreementClosed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [SignedBlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyBlueprint",
    values: [SignedBlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillOrder",
    values: [FillStruct, SignedBlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlueprintHash",
    values: [BlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignatureNow",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationLock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packDataField",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishBlueprint",
    values: [SignedBlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerLiquidation",
    values: [SignedBlueprintStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "unpackDataField",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BLUEPRINT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agreementClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destroyBlueprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlueprintHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignatureNow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packDataField",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishBlueprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpackDataField",
    data: BytesLike
  ): Result;
}

export namespace DestroyedBlueprintEvent {
  export type InputTuple = [blueprintHash: BytesLike];
  export type OutputTuple = [blueprintHash: string];
  export interface OutputObject {
    blueprintHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    agreement: SignedBlueprintStruct,
    orderBlueprintHash: BytesLike,
    taker: AddressLike
  ];
  export type OutputTuple = [
    agreement: SignedBlueprintStructOutput,
    orderBlueprintHash: string,
    taker: string
  ];
  export interface OutputObject {
    agreement: SignedBlueprintStructOutput;
    orderBlueprintHash: string;
    taker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    agreement: SignedBlueprintStruct,
    position: AddressLike,
    closer: AddressLike,
    closeValue: BigNumberish,
    loanOrcale: BigNumberish,
    assessorCost: BigNumberish
  ];
  export type OutputTuple = [
    agreement: SignedBlueprintStructOutput,
    position: string,
    closer: string,
    closeValue: bigint,
    loanOrcale: bigint,
    assessorCost: bigint
  ];
  export interface OutputObject {
    agreement: SignedBlueprintStructOutput;
    position: string;
    closer: string;
    closeValue: bigint;
    loanOrcale: bigint;
    assessorCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLiquidatedEvent {
  export type InputTuple = [
    agreement: SignedBlueprintStruct,
    position: AddressLike,
    liquidator: AddressLike
  ];
  export type OutputTuple = [
    agreement: SignedBlueprintStructOutput,
    position: string,
    liquidator: string
  ];
  export interface OutputObject {
    agreement: SignedBlueprintStructOutput;
    position: string;
    liquidator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublishedBlueprintEvent {
  export type InputTuple = [signedBlueprint: SignedBlueprintStruct];
  export type OutputTuple = [signedBlueprint: SignedBlueprintStructOutput];
  export interface OutputObject {
    signedBlueprint: SignedBlueprintStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsedBlueprintEvent {
  export type InputTuple = [operator: AddressLike, blueprintHash: BytesLike];
  export type OutputTuple = [operator: string, blueprintHash: string];
  export interface OutputObject {
    operator: string;
    blueprintHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bookkeeper extends BaseContract {
  connect(runner?: ContractRunner | null): Bookkeeper;
  waitForDeployment(): Promise<this>;

  interface: BookkeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BLUEPRINT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  PROTOCOL_NAME: TypedContractMethod<[], [string], "view">;

  PROTOCOL_VERSION: TypedContractMethod<[], [string], "view">;

  agreementClosed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  closePosition: TypedContractMethod<
    [agreementBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;

  destroyBlueprint: TypedContractMethod<
    [signedBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  fillOrder: TypedContractMethod<
    [fill: FillStruct, orderBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;

  getBlueprintHash: TypedContractMethod<
    [blueprint: BlueprintStruct],
    [string],
    "view"
  >;

  getChainId: TypedContractMethod<[], [bigint], "view">;

  isValidSignature: TypedContractMethod<
    [blueprintHash: BytesLike, arg1: BytesLike],
    [string],
    "view"
  >;

  isValidSignatureNow: TypedContractMethod<
    [signer: AddressLike, hash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  liquidationLock: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  packDataField: TypedContractMethod<
    [dataType: BytesLike, data: BytesLike],
    [string],
    "view"
  >;

  publishBlueprint: TypedContractMethod<
    [signedBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;

  triggerLiquidation: TypedContractMethod<
    [agreementBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;

  unpackDataField: TypedContractMethod<
    [data: BytesLike],
    [[string, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BLUEPRINT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agreementClosed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<
    [agreementBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroyBlueprint"
  ): TypedContractMethod<
    [signedBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fillOrder"
  ): TypedContractMethod<
    [fill: FillStruct, orderBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBlueprintHash"
  ): TypedContractMethod<[blueprint: BlueprintStruct], [string], "view">;
  getFunction(
    nameOrSignature: "getChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [blueprintHash: BytesLike, arg1: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidSignatureNow"
  ): TypedContractMethod<
    [signer: AddressLike, hash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidationLock"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "packDataField"
  ): TypedContractMethod<
    [dataType: BytesLike, data: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishBlueprint"
  ): TypedContractMethod<
    [signedBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerLiquidation"
  ): TypedContractMethod<
    [agreementBlueprint: SignedBlueprintStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpackDataField"
  ): TypedContractMethod<[data: BytesLike], [[string, string]], "view">;

  getEvent(
    key: "DestroyedBlueprint"
  ): TypedContractEvent<
    DestroyedBlueprintEvent.InputTuple,
    DestroyedBlueprintEvent.OutputTuple,
    DestroyedBlueprintEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLiquidated"
  ): TypedContractEvent<
    PositionLiquidatedEvent.InputTuple,
    PositionLiquidatedEvent.OutputTuple,
    PositionLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "PublishedBlueprint"
  ): TypedContractEvent<
    PublishedBlueprintEvent.InputTuple,
    PublishedBlueprintEvent.OutputTuple,
    PublishedBlueprintEvent.OutputObject
  >;
  getEvent(
    key: "UsedBlueprint"
  ): TypedContractEvent<
    UsedBlueprintEvent.InputTuple,
    UsedBlueprintEvent.OutputTuple,
    UsedBlueprintEvent.OutputObject
  >;

  filters: {
    "DestroyedBlueprint(bytes32)": TypedContractEvent<
      DestroyedBlueprintEvent.InputTuple,
      DestroyedBlueprintEvent.OutputTuple,
      DestroyedBlueprintEvent.OutputObject
    >;
    DestroyedBlueprint: TypedContractEvent<
      DestroyedBlueprintEvent.InputTuple,
      DestroyedBlueprintEvent.OutputTuple,
      DestroyedBlueprintEvent.OutputObject
    >;

    "OrderFilled(tuple,bytes32,address)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "PositionClosed(tuple,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionLiquidated(tuple,address,address)": TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;
    PositionLiquidated: TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;

    "PublishedBlueprint(tuple)": TypedContractEvent<
      PublishedBlueprintEvent.InputTuple,
      PublishedBlueprintEvent.OutputTuple,
      PublishedBlueprintEvent.OutputObject
    >;
    PublishedBlueprint: TypedContractEvent<
      PublishedBlueprintEvent.InputTuple,
      PublishedBlueprintEvent.OutputTuple,
      PublishedBlueprintEvent.OutputObject
    >;

    "UsedBlueprint(address,bytes32)": TypedContractEvent<
      UsedBlueprintEvent.InputTuple,
      UsedBlueprintEvent.OutputTuple,
      UsedBlueprintEvent.OutputObject
    >;
    UsedBlueprint: TypedContractEvent<
      UsedBlueprintEvent.InputTuple,
      UsedBlueprintEvent.OutputTuple,
      UsedBlueprintEvent.OutputObject
    >;
  };
}
