/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as plugins from "./plugins";
export type { plugins };
export type { Bookkeeper } from "./Bookkeeper";
