/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aggregatorV2V3InterfaceSol from "./AggregatorV2V3Interface.sol";
export type { aggregatorV2V3InterfaceSol };
