/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EIP712External } from "./EIP712External";
export type { ITractor } from "./ITractor";
export type { Tractor } from "./Tractor";
