/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BeanOracle } from "./BeanOracle";
export type { ChainlinkOracle } from "./ChainlinkOracle";
export type { StaticOracle } from "./StaticOracle";
