/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beanstalkSiloSol from "./BeanstalkSilo.sol";
export type { beanstalkSiloSol };
import type * as walletSol from "./Wallet.sol";
export type { walletSol };
